### ISSUE TITLE
"Enable TSID Matching" greyed out for non-shadow Pokémon

### ISSUE THREAD

**Issue by extherian** [ijuintekka/Eligor#2]
Eligor will allow me to generate valid PID/IV/Nature combinations for Espeon and Umbreon, however it will not allow me to tick "Enable TSID Matching" to match the values generated to those possible with my actual in-game Trainer ID and Secret ID. As a result, the Pokémon generated will always appear to be traded/foreign Pokémon.

Strictly speaking I could work around this by using PkmnGCSaveEditor to change my Trainer ID and Secret ID to match the generated Pokémon, but then my other starter will be seen as traded/foreign by the game. I see no reason for this limitation. Could you please lift it?

EDIT: Alternatively, could you allow valid PIDS to be generated for both Espeon and Umbreon from a given seed, as is already possible with various combinations of Pokémon XD shadow Pokémon.

**Comment by ijuintekka** [comment]
I wasn't able to reproduce your issue but I assume that by closing this you managed to figure it out.
